### ISSUE TITLE
[Bug]:Spark doesnt show in CD

### ISSUE THREAD

**Issue by XtarsAgency** [SunkyMP3G/Netronium#9]
### Description

Spark doesnt show in Core Database, even though it does show up in campaign

### Game build

146

### Other

- [X] I checked the other issues to make sure this bug isn't fixed

**Comment by SunkyMP3G** [comment]
It's used by enemies only for now. I already made an assembler for them, it will appear in 2nd sector.
It isn't hidden, just unaccessible
![image](https://github.com/SunkyMP3G/Netronium/assets/125795960/6992cfb9-fe02-49f3-ba3c-6e6dd4f4b5da)


###### ~~_And there's no 146 build, only 145.1_~~
